title: Semantiva framework
remote_theme: pages-themes/dinky@v0.2.0
plugins:
  - jekyll-remote-theme
theme: jekyll-theme-dinky 
description: An HPC-ready, domain-driven, type-oriented framework that delivers semantic transparency to advanced scientific computing.
baseurl: "/"

nav:
  - title: Home
    url: /
  - title: "1. Introduction"
    url: /1.Introduction/